# Generated by Django 4.0.6 on 2022-08-31 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_choice_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_title', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('employer', models.CharField(max_length=100)),
            ],
        ),
    ]
