# Generated by Django 4.0.6 on 2022-09-01 01:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Published'),
            preserve_default=False,
        ),
    ]
