# Generated by Django 4.0.6 on 2022-09-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_work_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='info',
            field=models.CharField(default='', max_length=300),
        ),
    ]
