# Generated by Django 4.0.6 on 2022-09-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_work_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='information',
            field=models.CharField(default='Ground receive for test bag center financial look. Act challenge best.\nPersonal yourself camera enjoy generation. Common that kitchen power cut. Threat camera herself back care phone country.', max_length=300),
        ),
    ]
