# Generated by Django 4.0.6 on 2022-09-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_work_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='information',
            field=models.CharField(max_length=300),
        ),
    ]
