# Generated by Django 4.0.6 on 2022-09-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_work_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='information',
            field=models.CharField(default='Involve magazine chair everybody. Loss establish say speak trouble allow policy project. Town difference party manage sit face real.', max_length=300),
        ),
    ]
