# Generated by Django 4.0.6 on 2022-09-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_work_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='information',
        ),
        migrations.AddField(
            model_name='work',
            name='info',
            field=models.CharField(default='Especially to reason forget. Notice since leg foot growth skill then. Reach discover carry soon wear trip detail.\nWater society start tend likely.', max_length=300),
        ),
    ]
