# Generated by Django 4.0.6 on 2022-09-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_work_information_work_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='info',
            field=models.CharField(max_length=300),
        ),
    ]
