# Generated by Django 4.0.6 on 2022-09-08 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_work_karmand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='karmand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.karmand'),
        ),
    ]
